# Generated by Django 5.2.1 on 2025-05-17 02:56

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description_simple', models.TextField(blank=True)),
                ('description_all', models.TextField(blank=True)),
                ('generical_name', models.CharField(blank=True, max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('utility', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medications',
                'ordering': ['id'],
            },
        ),
    ]
