# Generated by Django 5.2.1 on 2025-05-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationsmodel',
            name='datos',
            field=models.TextField(blank=True),
        ),
    ]
