# Generated by Django 5.2.1 on 2025-05-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_laboratorymodel_remove_medicationsmodel_datos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaboratoryModel',
        ),
    ]
