# Generated by Django 5.2.1 on 2025-05-17 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_laboratorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoriesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.TextField()),
                ('ruc', models.TextField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('dataset', models.TextField()),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
                'db_table': 'laboratories',
                'ordering': ['id'],
            },
        ),
    ]
