# Generated by Django 5.2.1 on 2025-05-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_laboratoriesmodel_dataset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaboratoriesModel',
            new_name='LaboratoryModel',
        ),
    ]
