# Generated by Django 5.2.1 on 2025-05-17 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_laboratoriesmodel_laboratorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.TextField()),
                ('ruc', models.TextField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LotModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='backend.medicationsmodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='backend.providermodel')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'lots',
                'ordering': ['id'],
            },
        ),
    ]
