# Generated by Django 5.2.1 on 2025-05-17 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_laboratorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
