# Generated by Django 5.2.1 on 2025-05-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_medicationsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationsmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicationsmodel',
            name='updated_at',
        ),
    ]
