# Generated by Django 5.2.1 on 2025-05-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_medicationsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationsmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
